### ISSUE TITLE
HTTP verb config snippet for PHP doesn't include DELETE

### ISSUE THREAD

**Issue by dtrenz** [SyntaxC4/MicrosoftAzureWebSitesCheatSheet#10]
How do I enable the DELETE verb for PHP? I tried simply adding DELETE to the comma-delimited verb list, but that doesn't seem to work.

**Comment by dtrenz** [comment]
It appears that there is an annoying bug in Azure where the DELETE verb won't work if it is the last verb in the list. I have not confirmed if this is true for any other verb, when last in the verb list.

Before I had:

``` xml
    <handlers>
            <remove name="PHP54_via_FastCGI" />
            <add name="PHP54_via_FastCGI"
                 path="*.php"
                 verb="GET, PUT, POST, HEAD, OPTIONS, DELETE"
                 modules="FastCgiModule"
                 scriptProcessor="D:\Program Files (x86)\PHP\v5.4\php-cgi.exe"
                 resourceType="Either"
                 requireAccess="Script" />
        </handlers>
```

...which did not work until I added another method to the end:

``` xml
    <handlers>
            <remove name="PHP54_via_FastCGI" />
            <add name="PHP54_via_FastCGI"
                 path="*.php"
                 verb="GET, PUT, POST, HEAD, OPTIONS, DELETE, PATCH"
                 modules="FastCgiModule"
                 scriptProcessor="D:\Program Files (x86)\PHP\v5.4\php-cgi.exe"
                 resourceType="Either"
                 requireAccess="Script" />
        </handlers>
```

**Comment by dtrenz** [comment]
Consider adding DELETE to the web.phpverbs.config, but be sure to add it anywhere but at the end of the list.

**Comment by SyntaxC4** [comment]
PRs are welcome. I'd rather see you get the credit for doing the investigation.

I'm going to repro and sent a bug to the IIS team to make sure this is either expected behavior or filed as a bug.

**Comment by dtrenz** [comment]
I'm not sure I can submit a PR for a Gist, can I?

**Comment by SyntaxC4** [comment]
Oh, you're right. I assumed if you could fork you could PR. Bad assumption on my part. **Updated**

**Comment by Rejoose** [comment]
Thnx Dtrenz.. Worked for me :+1:
